# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/E4_DialogUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 235)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(190, 180, 181, 32))
        self.buttonBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.minLevelLabel = QtWidgets.QLabel(Dialog)
        self.minLevelLabel.setGeometry(QtCore.QRect(20, 23, 231, 31))
        self.minLevelLabel.setObjectName("minLevelLabel")
        self.maxLevelLabel = QtWidgets.QLabel(Dialog)
        self.maxLevelLabel.setGeometry(QtCore.QRect(20, 70, 231, 41))
        self.maxLevelLabel.setObjectName("maxLevelLabel")
        self.maxLevelLabel_2 = QtWidgets.QLabel(Dialog)
        self.maxLevelLabel_2.setGeometry(QtCore.QRect(20, 120, 231, 41))
        self.maxLevelLabel_2.setObjectName("maxLevelLabel_2")
        self.minLevel = QtWidgets.QTextEdit(Dialog)
        self.minLevel.setGeometry(QtCore.QRect(250, 20, 121, 38))
        self.minLevel.setObjectName("minLevel")
        self.maxLevel = QtWidgets.QTextEdit(Dialog)
        self.maxLevel.setGeometry(QtCore.QRect(250, 70, 121, 38))
        self.maxLevel.setObjectName("maxLevel")
        self.bg = QtWidgets.QTextEdit(Dialog)
        self.bg.setGeometry(QtCore.QRect(250, 120, 121, 38))
        self.bg.setObjectName("bg")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Options"))
        self.minLevelLabel.setText(_translate("Dialog", "Select Minimum Grey Level"))
        self.maxLevelLabel.setText(_translate("Dialog", "Select Maximum Grey Level"))
        self.maxLevelLabel_2.setText(_translate("Dialog", "Retain Image Background?"))
